import 'package:flutter/material.dart';
import 'product.dart';

class MockData {
  MockData._();

  static const List<Map<String, dynamic>> categoryItems = [
    {'name': 'Lifestyle', 'icon': Icons.flash_on_rounded},
    {'name': 'Basketball', 'icon': Icons.sports_basketball_outlined},
    {'name': 'Running', 'icon': Icons.directions_run_rounded},
    {'name': 'Training', 'icon': Icons.fitness_center_rounded},
    {'name': 'Outdoor', 'icon': Icons.terrain_rounded},
  ];

  static const List<String> categories = [
    'Lifestyle',
    'Basketball',
    'Running',
    'Training',
    'Outdoor',
  ];

  static const List<String> brands = [
    'All Brands',
    'Nike',
    'Jordan',
    'Adidas',
    'New Balance',
  ];

  static const List<String> recentSearches = [
    'Air Max Pre-Day',
    'Creter Impact',
    'Air Max 90',
    'Space Hippie',
    'Air Force 1',
    'Dunk Low',
  ];

  static const List<String> popularSearches = [
    'Men\'s Shoes',
    'Running shoes',
    'Air Max',
    'Air Force 1',
    'Dunk Low',
    'VaporMax',
    'Metcon',
  ];

  static final List<Product> products = [
    Product(
      id: 'prod_preday',
      name: 'Air Max Pre-Day',
      brand: 'Nike',
      price: 137.50,
      originalPrice: 155.00,
      isSale: false,
      isNew: true,
      rating: 5.0,
      reviewCount: 1120,
      category: 'Lifestyle',
      description:
          'Taking the classic look of heritage Nike Running into a new realm, the Nike Air Max Pre-Day brings you a fast-paced look that\'s ready for today\'s world. Made with recycled materials, it combines the retro track aesthetic with a new Air window that energizes the look and feels unbelievably soft.',
      specs: {
        'Material': 'Sustainable recycled textile & soft synthetic suede',
        'Upper': 'Deconstructed upper with iconic large retro Swoosh',
        'Sole': 'Updated rubber Waffle sole with visible Air unit',
        'Fit': 'True to size with streamlined low-cut padded collar',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/air_max_preday_terracotta.png',
        'assets/images/air_max_preday_obsidian.png',
        'assets/images/air_max_preday_volt.png',
      ],
      availableColors: [
        ProductColor(name: 'Terracotta Red', color: Color(0xFFE85836)),
        ProductColor(name: 'Obsidian Grey', color: Color(0xFF161312)),
        ProductColor(name: 'Volt Lime', color: Color(0xFFC4E822)),
      ],
      availableSizes: [40, 41, 42, 43, 45, 46],
      outOfStockSizes: [45],
    ),
    Product(
      id: 'prod_crater',
      name: 'Creter Impact',
      brand: 'Nike',
      price: 99.56,
      originalPrice: 115.00,
      isSale: true,
      isNew: true,
      rating: 4.9,
      reviewCount: 840,
      category: 'Lifestyle',
      description:
          'Nike Crater Impact is part of our sustainability journey to transform trash into shoes that tread a little lighter. Made with at least 25% recycled material by weight, it brings unique design choices that reduce waste when compared with traditional methods.',
      specs: {
        'Material': 'Track-inspired silhouette with straight-edged overlays',
        'Upper': 'Breathable mesh upper with stitched webbing accents',
        'Sole': 'Lifted Crater foam midsole made from 12% recycled content',
        'Fit': 'Comfortable standard width with plush low collar',
        'Country': 'Indonesia',
      },
      images: [
        'assets/images/crater_impact_white.png',
        'assets/images/crater_impact_orange.png',
        'assets/images/crater_impact_obsidian.png',
      ],
      availableColors: [
        ProductColor(name: 'Summit White', color: Color(0xFFDFDFDF)),
        ProductColor(name: 'Terracotta Orange', color: Color(0xFFE85836)),
        ProductColor(name: 'Dark Obsidian', color: Color(0xFF161312)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44, 45],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_airmax90',
      name: 'Air Max 90 Terracotta',
      brand: 'Nike',
      price: 130.00,
      originalPrice: 160.00,
      isSale: true,
      isNew: false,
      rating: 4.95,
      reviewCount: 1240,
      category: 'Lifestyle',
      description:
          'Nothing as fly, nothing as proven. The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle sole, stitched overlays and classic TPU accents.',
      specs: {
        'Material': 'Stitched leather overlays and molded TPU accents',
        'Upper': 'Padded low-top collar that looks sleek and feels great',
        'Sole': 'Max Air unit in heel with rubber Waffle outsole',
        'Fit': 'True to size',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/air_max_90_terracotta.png',
        'assets/images/air_max_90_sand.png',
        'assets/images/air_max_90_black.png',
      ],
      availableColors: [
        ProductColor(name: 'Terracotta Orange', color: Color(0xFFE85836)),
        ProductColor(name: 'Sand Dune', color: Color(0xFFA98B73)),
        ProductColor(name: 'Midnight Black', color: Color(0xFF161312)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_af1',
      name: 'Air Force 1 \'07',
      brand: 'Nike',
      price: 115.00,
      originalPrice: 130.00,
      isSale: false,
      isNew: true,
      rating: 4.96,
      reviewCount: 2310,
      category: 'Lifestyle',
      description:
          'The radiance lives on in the Nike Air Force 1 \'07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold details and the perfect amount of flash.',
      specs: {
        'Material': 'Crisp, easy-to-clean leather overlays',
        'Upper': 'Perforations on the toe for breathability',
        'Sole': 'Nike Air cushioning with full pivot circular outsole',
        'Fit': 'Classic streetwear fit',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/air_force_1_white.png',
        'assets/images/air_force_1_black.png',
        'assets/images/air_force_1_terracotta.png',
      ],
      availableColors: [
        ProductColor(name: 'Triple White', color: Color(0xFFF5F5F5)),
        ProductColor(name: 'Triple Black', color: Color(0xFF1C1C1E)),
        ProductColor(name: 'Terracotta Red', color: Color(0xFFE85836)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44, 45, 46],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_dunk',
      name: 'Dunk Low Retro',
      brand: 'Nike',
      price: 125.00,
      originalPrice: 140.00,
      isSale: false,
      isNew: true,
      rating: 4.93,
      reviewCount: 1850,
      category: 'Basketball',
      description:
          'Created for the hardwood but taken to the streets, the \'80s b-ball icon returns with perfectly shined overlays and classic team colors with modern comfort.',
      specs: {
        'Material': 'Supple premium leather upper that ages to soft perfection',
        'Upper': 'Padded, low-cut collar looks sleek and feels comfortable',
        'Sole': 'Foam midsole offers lightweight, responsive cushioning',
        'Fit': 'Standard court fit',
        'Country': 'Indonesia',
      },
      images: [
        'assets/images/dunk_low_panda.png',
        'assets/images/dunk_low_unc.png',
        'assets/images/dunk_low_vintage.png',
      ],
      availableColors: [
        ProductColor(name: 'Panda White/Black', color: Color(0xFFDFDFDF)),
        ProductColor(name: 'UNC Carolina Blue', color: Color(0xFF2870B4)),
        ProductColor(name: 'Vintage Mocha', color: Color(0xFFBE966E)),
      ],
      availableSizes: [40, 41, 42, 43, 44, 45],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_vapormax',
      name: 'Air VaporMax Plus',
      brand: 'Nike',
      price: 210.00,
      originalPrice: null,
      isSale: false,
      isNew: true,
      rating: 4.91,
      reviewCount: 970,
      category: 'Lifestyle',
      description:
          'The Nike Air VaporMax Plus looks to the past and propels you into the future. Nodding to the 1998 Air Max Plus with its floating cage, padded upper and heel logo.',
      specs: {
        'Material': 'Synthetic floating cage with cushioned fabric',
        'Upper': 'Dynamic arch bringing beach life to the city',
        'Sole': 'VaporMax Air technology provides ultra lightweight bounce',
        'Fit': 'True to size snug runner fit',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/vapormax_sunset.png',
        'assets/images/vapormax_triple_black.png',
        'assets/images/vapormax_ice_blue.png',
      ],
      availableColors: [
        ProductColor(name: 'Sunset Orange', color: Color(0xFFE85836)),
        ProductColor(name: 'Triple Black', color: Color(0xFF161312)),
        ProductColor(name: 'Ice Blue', color: Color(0xFF328CD2)),
      ],
      availableSizes: [40, 41, 42, 43, 44, 45, 46],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_spacehippie',
      name: 'Space Hippie 04',
      brand: 'Nike',
      price: 130.00,
      originalPrice: null,
      isSale: false,
      isNew: true,
      rating: 4.85,
      reviewCount: 460,
      category: 'Running',
      description:
          'Space Hippie is an exploratory footwear collection inspired by life on Mars. From the upper to the outsole, Space Hippie 04 is made with at least 25% recycled material by weight.',
      specs: {
        'Material': 'Space Waste Yarn upper made from recycled plastic bottles',
        'Upper': 'Lightweight and stretchy Flyknit construction',
        'Sole': 'Crater Foam midsole combining Nike Grind with foam blends',
        'Fit': 'Snug sock-like fit',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/space_hippie_orange.png',
        'assets/images/space_hippie_black.png',
        'assets/images/space_hippie_blue.png',
      ],
      availableColors: [
        ProductColor(name: 'Orange Volt', color: Color(0xFFE85836)),
        ProductColor(name: 'Midnight Black', color: Color(0xFF161312)),
        ProductColor(name: 'Royal Cobalt', color: Color(0xFF2B5B84)),
      ],
      availableSizes: [40, 41, 42, 43, 44, 45],
      outOfStockSizes: [40],
    ),
    Product(
      id: 'prod_blazer',
      name: 'Blazer Mid 77 Vintage',
      brand: 'Nike',
      price: 105.00,
      originalPrice: null,
      isSale: false,
      isNew: false,
      rating: 4.88,
      reviewCount: 910,
      category: 'Basketball',
      description:
          'In the \'70s, Nike was the new shoe on the block. The Nike Blazer Mid \'77 Vintage harnesses the old-school look of Nike basketball with a vintage midsole finish.',
      specs: {
        'Material': 'Leather and synthetic upper maintains the classic look',
        'Upper': 'Exposed foam tongue provides a retro feel',
        'Sole': 'Solid-rubber outsole with herringbone pattern for traction',
        'Fit': 'Snug retro court fit',
        'Country': 'Indonesia',
      },
      images: [
        'assets/images/blazer_mid_white.png',
        'assets/images/blazer_mid_red.png',
        'assets/images/blazer_mid_navy.png',
      ],
      availableColors: [
        ProductColor(name: 'White / Black Swoosh', color: Color(0xFFDFDFDF)),
        ProductColor(name: 'Terracotta Team Red', color: Color(0xFFE85836)),
        ProductColor(name: 'Court Blue', color: Color(0xFF254B73)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44, 45, 46],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_react',
      name: 'React Infinity 3',
      brand: 'Nike',
      price: 160.00,
      originalPrice: 175.00,
      isSale: true,
      isNew: true,
      rating: 4.89,
      reviewCount: 780,
      category: 'Running',
      description:
          'Still our most tested shoe, created to help you pursue high running goals. The Nike React Infinity 3 feels soft and stable with a smooth ride that carries you through routes.',
      specs: {
        'Material': 'Flyknit upper creates specific zones of breathability',
        'Upper': 'Flywire technology offers midfoot support',
        'Sole': 'Nike React technology with rocker-shaped sole',
        'Fit': 'Plush cushioned marathon fit',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/react_infinity_white.png',
        'assets/images/react_infinity_crimson.png',
        'assets/images/react_infinity_volt.png',
      ],
      availableColors: [
        ProductColor(name: 'Pure Platinum', color: Color(0xFFEBEBEB)),
        ProductColor(name: 'Crimson Orange', color: Color(0xFFE85836)),
        ProductColor(name: 'Volt Flash', color: Color(0xFFB4E11E)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44, 45],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_metcon',
      name: 'Metcon 8 Training',
      brand: 'Nike',
      price: 130.00,
      originalPrice: null,
      isSale: false,
      isNew: true,
      rating: 4.94,
      reviewCount: 1420,
      category: 'Training',
      description:
          'You chase the clock, challenging and encouraging each other all in the name of achieving goals. Our go-to model for training relies on a lighter, more breathable upper than previous editions.',
      specs: {
        'Material': 'Textured mesh with durable overlays in high-wear areas',
        'Upper': 'Tab locks down laces with a hook-and-loop closure',
        'Sole': 'Wide, flat heel gets even more stable with inner plate',
        'Fit': 'Locked-in cross-training stability',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/metcon_8_grey.png',
        'assets/images/metcon_8_black.png',
        'assets/images/metcon_8_orange.png',
      ],
      availableColors: [
        ProductColor(name: 'Smoke Grey', color: Color(0xFFE6E6E6)),
        ProductColor(name: 'Anthracite Black', color: Color(0xFF1E1E23)),
        ProductColor(name: 'Terracotta Fire', color: Color(0xFFE85836)),
      ],
      availableSizes: [40, 41, 42, 43, 44, 45, 46],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_acg',
      name: 'ACG Mountain Fly Low',
      brand: 'Nike',
      price: 150.00,
      originalPrice: 170.00,
      isSale: true,
      isNew: false,
      rating: 4.87,
      reviewCount: 520,
      category: 'Outdoor',
      description:
          'Fast, rugged and as at home in the city as it is on rocky trails, the Nike ACG Mountain Fly Low is ready for whatever you can throw at it.',
      specs: {
        'Material': 'Lightweight ripstop and synthetic upper for durability',
        'Upper': 'Ghillie lacing system creates a personalized fit',
        'Sole': 'Hard rubber wraps onto the toe and thick chevron lugs',
        'Fit': 'Rugged all-conditions outdoor grip',
        'Country': 'China',
      },
      images: [
        'assets/images/acg_mountain_sand.png',
        'assets/images/acg_mountain_olive.png',
        'assets/images/acg_mountain_anthracite.png',
      ],
      availableColors: [
        ProductColor(name: 'Desert Sand', color: Color(0xFFD2B48C)),
        ProductColor(name: 'Cargo Olive', color: Color(0xFF4B5F3C)),
        ProductColor(name: 'Anthracite', color: Color(0xFF232328)),
      ],
      availableSizes: [40, 41, 42, 43, 44, 45],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_pegasus_trail',
      name: 'Pegasus Trail 4 GTX',
      brand: 'Nike',
      price: 165.00,
      originalPrice: null,
      isSale: false,
      isNew: true,
      rating: 4.91,
      reviewCount: 630,
      category: 'Outdoor',
      description:
          'The Nike Pegasus Trail 4 GORE-TEX is your running companion for those days when the weather turns. Its waterproof GORE-TEX layer keeps your feet dry.',
      specs: {
        'Material': 'GORE-TEX invisible fit waterproof membrane',
        'Upper': 'Ankle gaiter keeps trail debris and water out',
        'Sole': 'Generative traction pattern combined with rubber in forefoot',
        'Fit': 'Comfortable waterproof trail ride',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/pegasus_trail_khaki.png',
        'assets/images/pegasus_trail_sunset.png',
        'assets/images/pegasus_trail_black.png',
      ],
      availableColors: [
        ProductColor(name: 'Golden Khaki', color: Color(0xFFC8AF8C)),
        ProductColor(name: 'Sunset Terracotta', color: Color(0xFFE85836)),
        ProductColor(name: 'Black Shadow', color: Color(0xFF232328)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44, 45, 46],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_superrep',
      name: 'SuperRep Go 3 Flyknit',
      brand: 'Nike',
      price: 120.00,
      originalPrice: null,
      isSale: false,
      isNew: true,
      rating: 4.82,
      reviewCount: 390,
      category: 'Training',
      description:
          'The new Nike SuperRep Go 3 Flyknit is a radical design story rooted in sustainability and innovation. The zoned Flyknit construction wraps your foot in 360 degrees of comfort.',
      specs: {
        'Material': 'Modified Flyknit upper made with recycled material',
        'Upper': 'Strategic containment during fast, active movements',
        'Sole': 'Finely ground foam in midsole gives responsive comfort',
        'Fit': 'Flexible HIIT and circuit training fit',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/superrep_neon.png',
        'assets/images/superrep_pink.png',
        'assets/images/superrep_black.png',
      ],
      availableColors: [
        ProductColor(name: 'Volt Neon', color: Color(0xFFB4E628)),
        ProductColor(name: 'Hyper Pink', color: Color(0xFFDC3C78)),
        ProductColor(name: 'Midnight Black', color: Color(0xFF232328)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_lebron',
      name: 'LeBron Witness 7',
      brand: 'Nike',
      price: 105.00,
      originalPrice: 125.00,
      isSale: true,
      isNew: false,
      rating: 4.86,
      reviewCount: 810,
      category: 'Basketball',
      description:
          'The longer LeBron\'s legendary career continues, the more his game needs a design that doesn\'t weigh him down yet can still control all that sublime power.',
      specs: {
        'Material': 'Breathable mesh upper with reinforced stitching',
        'Upper': 'Molded fin on heel provides lockdown support',
        'Sole': 'Full-length Max Air unit encapsulated in low-profile midsole',
        'Fit': 'Dynamic high-impact basketball lockdown',
        'Country': 'China',
      },
      images: [
        'assets/images/lebron_witness_purple.png',
        'assets/images/lebron_witness_gold.png',
        'assets/images/lebron_witness_black.png',
      ],
      availableColors: [
        ProductColor(name: 'Lakers Purple', color: Color(0xFF6E2D96)),
        ProductColor(name: 'Championship Gold', color: Color(0xFFD7A528)),
        ProductColor(name: 'Midnight Stealth', color: Color(0xFF232328)),
      ],
      availableSizes: [40, 41, 42, 43, 44, 45, 46],
      outOfStockSizes: [],
    ),
    Product(
      id: 'prod_pegasus',
      name: 'Air Zoom Pegasus 38',
      brand: 'Nike',
      price: 120.00,
      originalPrice: 140.00,
      isSale: true,
      isNew: false,
      rating: 4.92,
      reviewCount: 670,
      category: 'Running',
      description:
          'Your workhorse with wings returns. The Nike Air Zoom Pegasus 38 continues to put a spring in your step, using the same responsive React foam as its predecessor.',
      specs: {
        'Material': 'Engineered sandwich mesh upper',
        'Upper': 'Midfoot webbing for a secure snug lockdown',
        'Sole': 'Nike React foam with forefoot Zoom Air unit',
        'Fit': 'Wider toe box for enhanced running comfort',
        'Country': 'Vietnam',
      },
      images: [
        'assets/images/pegasus_crimson.png',
        'assets/images/pegasus_black.png',
        'assets/images/pegasus_teal.png',
      ],
      availableColors: [
        ProductColor(name: 'Crimson Tint', color: Color(0xFFE85836)),
        ProductColor(name: 'Pure Black', color: Color(0xFF161312)),
        ProductColor(name: 'Emerald Teal', color: Color(0xFF1D6F60)),
      ],
      availableSizes: [39, 40, 41, 42, 43, 44, 45],
      outOfStockSizes: [],
    ),
  ];

  static const Address initialAddress = Address(
    id: 'addr_1',
    name: 'Irtaza Khalid',
    phone: '+1 (555) 234-8901',
    street: '742 Evergreen Terrace, Suite 4B',
    city: 'San Francisco, CA',
    postalCode: '94107',
    isDefault: true,
  );

  static final UserProfile initialProfile = UserProfile(
    name: 'Munib',
    email: 'munib.designer@nws.studio',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    addresses: [initialAddress],
    paymentMethods: [
      'Apple Pay (Default)',
      'Visa ending in •••• 4242',
      'Mastercard ending in •••• 8819',
    ],
  );

  static final List<Order> initialOrders = [
    Order(
      id: 'NWS10248',
      items: [
        CartItem(
          product: products[0],
          selectedColor: products[0].availableColors[0],
          selectedSize: 42,
          quantity: 1,
        ),
      ],
      subtotal: 137.50,
      shippingFee: 10.0,
      discount: 0.0,
      total: 147.50,
      status: OrderStatus.shipped,
      shippingAddress: initialAddress,
      paymentMethod: 'Apple Pay',
      trackingNumber: 'NWS-TRK-9821739',
      carrier: 'FedEx Express Sneaker Priority',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      estimatedDelivery: 'Aug 20–22',
    ),
  ];
}
